# Generated by Django 3.0.4 on 2020-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200420_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(max_length=255, upload_to='projects/images', verbose_name='Imagem de capa:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(max_length=255, upload_to='projects/files', verbose_name='Arquivos do projeto:'),
        ),
    ]
