# Generated by Django 3.0.4 on 2020-03-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id', 'name', 'email', 'phone', 'message', 'created_at', 'updated_at'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
