# Generated by Django 3.0.4 on 2020-03-21 11:32

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=froala_editor.fields.FroalaField(verbose_name='Conteúdo:'),
        ),
    ]
