# Generated by Django 3.0.4 on 2020-04-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200321_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-id'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
