# Generated by Django 3.0.4 on 2020-04-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200314_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
