# Generated by Django 3.0.4 on 2020-05-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200418_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Telefone de contato:'),
        ),
    ]
