# Generated by Django 3.0.4 on 2020-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35)),
                ('content', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('Y', 'Ativa'), ('N', 'Desativada')], default='Y', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
