# Generated by Django 3.0.4 on 2020-03-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35, verbose_name='Título:')),
                ('content', models.TextField(verbose_name='Conteúdo:')),
                ('slug', models.SlugField(verbose_name='Identificador:')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['id', 'title', 'content', 'slug', 'status', 'created_at', 'updated_at'],
            },
        ),
    ]
