# Generated by Django 3.0.4 on 2020-03-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id', 'title', 'content', 'slug', 'status', 'created_at', 'updated_at'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
