# Generated by Django 3.0.4 on 2020-03-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200314_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(max_length=150, verbose_name='Conteúdo:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(verbose_name='Identificador:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Título:'),
        ),
    ]
