# Generated by Django 3.0.4 on 2020-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200418_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='projects', verbose_name='Imagem de capa:'),
        ),
    ]
