# Generated by Django 3.0.4 on 2020-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200420_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, max_length=255, upload_to='projects/files', verbose_name='Arquivos do projeto:'),
        ),
    ]
