# Generated by Django 3.0.4 on 2020-04-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200420_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
    ]
