# Generated by Django 3.0.4 on 2020-04-20 22:31

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome:')),
                ('version', models.CharField(max_length=50, verbose_name='Versão:')),
                ('content', froala_editor.fields.FroalaField(verbose_name='Descrição:')),
                ('files', models.ImageField(max_length=255, upload_to='projects/images', verbose_name='Arquivos do projeto:')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-id'],
            },
        ),
    ]
