# Generated by Django 3.0.4 on 2020-05-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_registerdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome completo:')),
                ('email', models.EmailField(max_length=40, verbose_name='Email de contato:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='projects.File')),
            ],
            options={
                'verbose_name': 'Registro de download',
                'verbose_name_plural': 'Registro de download',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='RegisterDownload',
        ),
    ]
