# Generated by Django 3.0.4 on 2020-03-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Nome:')),
                ('description_short', models.CharField(max_length=50, verbose_name='Descrição curta:')),
                ('slug', models.SlugField(verbose_name='Identificador:')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbums',
                'ordering': ['id', 'name', 'description_short', 'created_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Foto:')),
                ('description_short', models.CharField(max_length=50, verbose_name='Descrição curta:')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.Album')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['id', 'photo', 'description_short', 'created_at', 'updated_at'],
            },
        ),
    ]
