# Generated by Django 3.0.4 on 2020-04-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-id'], 'verbose_name': 'Álbum', 'verbose_name_plural': 'Álbums'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
