# Generated by Django 3.0.4 on 2020-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20200418_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='albuns', verbose_name='Imagem de capa:'),
        ),
    ]
