# Generated by Django 3.0.4 on 2020-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20200420_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(max_length=255, upload_to='albums', verbose_name='Imagem de capa:'),
        ),
    ]
